language: java
node_js:
    - "0.12"
install: true
script:
    - TERM=dumb ./gradlew build jacocoTestReport
jdk:
    - oraclejdk7
before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - "npm install -g typescript@1.4.1"
after_success:
    ./gradlew jacocoRootReport coveralls -i
